"use client"

import { useEffect, useState } from "react"
import { ChevronDown, Mail, MessageCircle, Phone, Send } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { useLocale } from "@/lib/locale-context"
import { DEFAULT_STORE_SETTINGS, fetchStoreSettings, loadStoreSettings, toTelUrl, toWhatsAppUrl } from "@/lib/store-settings"

const faqs = [
  { q: { fr: "Comment suivre ma commande ?", ar: "كيف أتابع طلبي؟" }, a: { fr: "Connectez-vous à votre compte puis ouvrez la section Commandes. Vous y retrouverez la référence et l’état réel de chaque commande.", ar: "سجل الدخول إلى حسابك ثم افتح قسم الطلبات لمعرفة المرجع والحالة الحالية." } },
  { q: { fr: "Quels modes de paiement sont disponibles ?", ar: "ما هي طرق الدفع المتاحة؟" }, a: { fr: "Le checkout propose les méthodes actuellement configurées : paiement à la réception, CIB, Edahabia et virement bancaire.", ar: "تتوفر طرق الدفع المهيأة حالياً: الدفع عند الاستلام و CIB والذهبية والتحويل البنكي." } },
  { q: { fr: "Comment vous contacter au sujet d’une commande ?", ar: "كيف أتواصل معكم بخصوص طلب؟" }, a: { fr: "Indiquez votre référence de commande et contactez-nous via WhatsApp, téléphone ou email. Notre équipe pourra vous répondre plus précisément.", ar: "أرسل رقم طلبك وتواصل معنا عبر واتساب أو الهاتف أو البريد الإلكتروني لمساعدتك بشكل أدق." } },
]

export default function SupportPage() {
  const { locale } = useLocale(); const isArabic = locale === "ar"; const [settings, setSettings] = useState(DEFAULT_STORE_SETTINGS)
  useEffect(() => { let active = true; fetchStoreSettings().then((value) => { if (active) setSettings(value) }).catch(() => { if (active) setSettings(loadStoreSettings()) }); return () => { active = false } }, [])
  const contacts = [{ icon: MessageCircle, label: "WhatsApp", value: settings.whatsapp, href: toWhatsAppUrl(settings.whatsapp) }, { icon: Phone, label: isArabic ? "الهاتف" : "Téléphone", value: settings.phonePrimary, href: toTelUrl(settings.phonePrimary) }, { icon: Mail, label: "Email", value: settings.contactEmail, href: `mailto:${settings.contactEmail}` }]
  return <main dir={isArabic ? "rtl" : "ltr"} className="mx-auto max-w-[1100px] px-5 py-10 sm:px-8 sm:py-14 lg:px-12 lg:py-16"><header className="max-w-2xl"><p className="text-[11px] font-semibold uppercase tracking-[0.25em] text-primary">Edigiya / {isArabic ? "المساعدة" : "Support"}</p><h1 className="mt-4 font-heading text-4xl font-semibold tracking-tight sm:text-5xl">{isArabic ? "نحن هنا لمساعدتك." : "Nous sommes là pour vous aider."}</h1><p className="mt-5 text-base leading-7 text-muted-foreground">{isArabic ? "سؤال حول منتج أو طلب؟ تواصل معنا بالطريقة التي تناسبك." : "Une question sur un produit ou une commande ? Choisissez le canal qui vous convient."}</p></header><div className="mt-12 grid gap-4 sm:grid-cols-3">{contacts.map(({ icon: Icon, label, value, href }) => <a key={label} href={href} target="_blank" rel="noopener noreferrer" className="group border border-border bg-card p-5 transition-colors hover:border-primary"><Icon className="h-5 w-5 text-primary" /><p className="mt-8 text-sm font-semibold">{label}</p><p className="mt-1 truncate text-xs text-muted-foreground">{value}</p></a>)}</div><div className="mt-16 grid gap-12 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-primary">Questions fréquentes</p><h2 className="mt-3 font-heading text-2xl font-semibold">{isArabic ? "إجابات واضحة." : "Des réponses claires."}</h2></div><Accordion type="single" collapsible className="border-y border-border">{faqs.map((faq, index) => <AccordionItem key={faq.q.fr} value={`faq-${index}`}><AccordionTrigger className="py-5 text-start text-sm font-medium hover:no-underline">{faq.q[locale]}</AccordionTrigger><AccordionContent className="pb-5 text-sm leading-7 text-muted-foreground">{faq.a[locale]}</AccordionContent></AccordionItem>)}</Accordion></div><div className="mt-16 flex flex-col items-start justify-between gap-6 border-t border-border pt-8 sm:flex-row sm:items-center"><div><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-primary">{isArabic ? "تحتاج إلى مساعدة؟" : "Besoin d’aide ?"}</p><h2 className="mt-2 font-heading text-xl font-semibold">{isArabic ? "تحدث مع فريق Edigiya." : "Parlez avec l’équipe Edigiya."}</h2></div><a href={toWhatsAppUrl(settings.whatsapp)} target="_blank" rel="noopener noreferrer"><Button className="gap-2"><MessageCircle className="h-4 w-4" />{isArabic ? "التحدث عبر واتساب" : "Parler sur WhatsApp"}<Send className="h-3.5 w-3.5" /></Button></a></div></main>
}
