#!/bin/bash
# QUICK START GUIDE - ERP System Setup

echo "==================================="
echo "ERP System - Quick Start"
echo "==================================="
echo ""

echo "📍 PROJECT LOCATION"
echo "c:\Users\codem\OneDrive\project\nutrition-erp"
echo ""

echo "✅ FILES CREATED"
echo "  ├── SQL Schema: sql/001_create_erp_tables.sql"
echo "  ├── Types: src/types/index.ts"
echo "  ├── Services:"
echo "  │   ├── salesService.ts (Order fulfillment + FIFO)"
echo "  │   ├── purchaseService.ts (Supplier purchases)"
echo "  │   ├── stockService.ts (Inventory management)"
echo "  │   ├── cashService.ts (Financial ledger)"
echo "  │   └── index.ts (Service exports)"
echo "  └── Documentation:"
echo "      ├── README.md (Full architecture)"
echo "      ├── USAGE_EXAMPLES.md (Practical scenarios)"
echo "      └── SETUP_SUMMARY.md (This guide)"
echo ""

echo "🚀 STEP 1: Run SQL Migration"
echo "  → Copy all SQL from: sql/001_create_erp_tables.sql"
echo "  → Run in Supabase > SQL Editor"
echo "  → Creates 7 tables + 3 views"
echo ""

echo "💰 STEP 2: Initialize Cash Ledger"
echo "  import { cashService } from '@/services';"
echo "  await cashService.initializeCashLedger(100000); // Opening balance"
echo ""

echo "📝 STEP 3: Create First Supplier"
echo "  const supplier = await supabase"
echo "    .from('suppliers')"
echo "    .insert({ name: 'ABC Distributor', ... })"
echo ""

echo "🛒 STEP 4: Create Purchase Order"
echo "  import { purchaseService } from '@/services';"
echo "  const po = await purchaseService.createPurchase("
echo "    { supplier_id: 1, purchase_date: '2024-04-21' },"
echo "    [{ product_id: 5, quantity_ordered: 100, unit_cost: 50 }]"
echo "  );"
echo ""

echo "📦 STEP 5: Receive Stock"
echo "  await purchaseService.receiveStock(po.id, ["
echo "    {"
echo "      purchase_item_id: 1,"
echo "      product_id: 5,"
echo "      quantity_received: 100,"
echo "      batch_number: 'BATCH-001',"
echo "      unit_cost: 50,"
echo "      received_date: '2024-04-21'"
echo "    }"
echo "  ]);"
echo ""

echo "💳 STEP 6: Pay for Purchase"
echo "  await purchaseService.processPurchasePayment(po.id, 5000);"
echo ""

echo "🎯 STEP 7: Process Order Sale"
echo "  import { salesService } from '@/services';"
echo "  await salesService.processOrderSale(orderId, 2500, 'cash');"
echo "  → Deducts stock using FIFO"
echo "  → Records cash inflow"
echo ""

echo "📊 STEP 8: Check Balances"
echo "  const balance = await cashService.getCashBalance();"
echo "  const stock = await stockService.getStockLevel(5);"
echo "  const ledger = await cashService.getCashLedger('2024-04-01', '2024-04-30');"
echo ""

echo "==================================="
echo "🔑 KEY CONCEPTS"
echo "==================================="
echo ""

echo "1️⃣  FIFO Stock Deduction"
echo "   - Oldest batches consumed first"
echo "   - Batches ordered by received_date"
echo "   - Used in salesService.processOrderSale()"
echo ""

echo "2️⃣  Cash Ledger (Single Source of Truth)"
echo "   - All transactions recorded with debit/credit"
echo "   - Balance is running sum of transactions"
echo "   - Immutable (created_at only, no updates)"
echo ""

echo "3️⃣  Stock Movements (Audit Trail)"
echo "   - Every stock change recorded"
echo "   - movement_type: in|out|adjustment|damage|return"
echo "   - Immutable for compliance"
echo ""

echo "4️⃣  Traceability"
echo "   - reference_id + reference_type"
echo "   - Links transactions to source (order, purchase)"
echo "   - Complete audit capability"
echo ""

echo "==================================="
echo "📚 DOCUMENTATION"
echo "==================================="
echo ""
echo "READ IN ORDER:"
echo "1. README.md - Full architecture & database schema"
echo "2. USAGE_EXAMPLES.md - Real-world code examples"
echo "3. Service files - Implementation details"
echo ""

echo "==================================="
echo "⚠️  IMPORTANT"
echo "==================================="
echo ""
echo "✅ DO:"
echo "  • Use FIFO for all stock deductions"
echo "  • Record all cash in cash_ledger"
echo "  • Include batch_number for traceability"
echo "  • Validate cash balance before payments"
echo ""

echo "❌ DON'T:"
echo "  • Modify existing tables (products, orders, etc.)"
echo "  • Delete from stock_movements or cash_ledger"
echo "  • Deduct stock without using deductStockFIFO()"
echo "  • Store balance outside of cash_ledger"
echo ""

echo "==================================="
echo "✅ SETUP COMPLETE!"
echo "==================================="
