#!/bin/bash

# 🚀 PROJECT SETUP GUIDE
# =====================================================================

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  NUTRITION ERP - PROJECT SETUP COMPLETE                       ║"
echo "║  Tauri + React + TypeScript + Supabase                        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📦 INSTALLATION STEPS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  Install Dependencies"
echo "────────────────────────"
echo "   Command: npm install"
echo "   Time: ~2-3 minutes"
echo "   Status: Installing Node modules, Tauri CLI, React, etc."
echo ""

echo "2️⃣  Configure Supabase"
echo "──────────────────────"
echo "   File: .env.local"
echo "   Action: Add your Supabase project details"
echo "   Fields:"
echo "     • VITE_SUPABASE_URL=https://your-project.supabase.co"
echo "     • VITE_SUPABASE_ANON_KEY=your-anon-key-here"
echo ""

echo "3️⃣  Configure Database"
echo "──────────────────────"
echo "   Location: sql/001_create_erp_tables.sql"
echo "   Steps:"
echo "     • Open Supabase Dashboard"
echo "     • Go to SQL Editor"
echo "     • Create new query"
echo "     • Copy entire contents of sql/001_create_erp_tables.sql"
echo "     • Run the query"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "🎯 START DEVELOPMENT"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "Option 1: Web Development (for frontend work)"
echo "──────────────────────────────────────────────"
echo "   Command: npm run dev"
echo "   Opens: http://localhost:5173"
echo "   Uses: Vite dev server with hot reload"
echo "   Status: Frontend + Services ready"
echo ""

echo "Option 2: Desktop Development (full Tauri)"
echo "────────────────────────────────────────────"
echo "   Command: npm run tauri dev"
echo "   Opens: Tauri desktop window"
echo "   Includes: Rust backend + React frontend"
echo "   Requires: Rust toolchain installed"
echo ""

echo "Option 3: Production Build"
echo "──────────────────────────"
echo "   Command: npm run build"
echo "   Creates: Optimized desktop application"
echo "   Output: Installer in src-tauri/target/release/bundle"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "✅ PROJECT STRUCTURE"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "Frontend (React)"
echo "────────────────"
echo "  src/"
echo "  ├── main.tsx          → React entry point"
echo "  ├── App.tsx            → Main application component"
echo "  ├── App.css            → Application styles"
echo "  ├── index.css          → Global styles"
echo "  ├── services/          → Backend service integrations"
echo "  │   ├── salesService.ts"
echo "  │   ├── purchaseService.ts"
echo "  │   ├── stockService.ts"
echo "  │   ├── cashService.ts"
echo "  │   └── index.ts"
echo "  └── types/             → TypeScript type definitions"
echo "      └── index.ts"
echo ""

echo "Configuration"
echo "──────────────"
echo "  ├── package.json        → Node.js project config"
echo "  ├── tsconfig.json       → TypeScript config"
echo "  ├── vite.config.ts      → Vite build config"
echo "  ├── index.html          → HTML entry point"
echo "  ├── .env.local          → Environment variables"
echo "  └── .env.example        → Example env file"
echo ""

echo "Backend (Tauri + Rust)"
echo "──────────────────────"
echo "  src-tauri/"
echo "  ├── tauri.conf.json     → Tauri app config"
echo "  ├── Cargo.toml          → Rust dependencies"
echo "  ├── build.rs            → Tauri build script"
echo "  └── src/"
echo "      └── main.rs         → Rust entry point"
echo ""

echo "Database (PostgreSQL)"
echo "────────────────────"
echo "  sql/"
echo "  └── 001_create_erp_tables.sql"
echo "      ├── Tables: suppliers, purchases, purchase_items"
echo "      ├──         stock_batches, stock_movements"
echo "      ├──         expenses, cash_ledger"
echo "      ├── Views: stock_levels, cash_summary, purchase_summary"
echo "      └── Functions: deduct_stock_fifo(), get_current_cash_balance()"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "📊 SERVICES OVERVIEW"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "Sales Service (salesService.ts)"
echo "───────────────────────────────"
echo "  • processOrderSale() - Create and process sales orders"
echo "  • deductStockFIFOAtomic() - Atomic FIFO stock deduction"
echo "  • getCurrentCashBalance() - Get current cash balance"
echo "  • getSalesSummary() - Get sales analytics"
echo ""

echo "Purchase Service (purchaseService.ts)"
echo "─────────────────────────────────────"
echo "  • createPurchase() - Create purchase orders"
echo "  • receiveStock() - Receive stock from suppliers"
echo "  • processPurchasePayment() - Process payments"
echo "  • getPurchaseSummary() - Get purchase analytics"
echo ""

echo "Stock Service (stockService.ts)"
echo "───────────────────────────────"
echo "  • getStockLevel() - Get current stock quantities"
echo "  • getProductBatches() - Get FIFO ordered batches"
echo "  • recordStockAdjustment() - Record inventory adjustments"
echo "  • getStockHistory() - Get inventory audit trail"
echo "  • getLowStockProducts() - Get low stock alerts"
echo ""

echo "Cash Service (cashService.ts)"
echo "─────────────────────────────"
echo "  • getCashBalance() - Get current cash balance"
echo "  • getCashSummary() - Get cash summary"
echo "  • getCashLedger() - Get transaction history"
echo "  • recordTransaction() - Record cash transactions"
echo "  • validateLedgerIntegrity() - Verify cash ledger"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "🔧 USEFUL COMMANDS"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "Development"
echo "───────────"
echo "  npm run dev              → Start dev server (web)"
echo "  npm run tauri dev        → Start Tauri desktop dev"
echo "  npm run preview          → Preview production build"
echo ""

echo "Building"
echo "────────"
echo "  npm run build            → Build desktop app"
echo "  npm run type-check       → Check TypeScript types"
echo ""

echo "Code Quality"
echo "───────────"
echo "  npm run lint             → Check code with ESLint"
echo "  npm run format           → Format code with Prettier"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "📚 DOCUMENTATION"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "Start Here"
echo "──────────"
echo "  • 00_START_HERE.md"
echo "  • QUICK_START.sh"
echo "  • QUICK_REFERENCE_CARD.sh"
echo ""

echo "Implementation"
echo "──────────────"
echo "  • TRANSACTIONAL_IMPLEMENTATION_SUMMARY.md"
echo "  • DEPLOYMENT_CHECKLIST.md"
echo "  • MIGRATION_GUIDE.sh"
echo ""

echo "Technical Details"
echo "─────────────────"
echo "  • TRANSACTIONAL_SAFETY.md"
echo "  • BEFORE_AFTER_COMPARISON.md"
echo "  • SQL_REFERENCE_GUIDE.md"
echo ""

echo "Architecture"
echo "─────────────"
echo "  • README.md"
echo "  • SETUP_SUMMARY.md"
echo "  • USAGE_EXAMPLES.md"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "🎯 NEXT STEPS"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "1. Configure Supabase"
echo "   └─ Edit: .env.local"
echo "   └─ Add your VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY"
echo ""

echo "2. Setup Database"
echo "   └─ Copy sql/001_create_erp_tables.sql"
echo "   └─ Run in Supabase SQL Editor"
echo ""

echo "3. Start Development"
echo "   └─ Run: npm run dev"
echo "   └─ Open: http://localhost:5173"
echo ""

echo "4. Build Components"
echo "   └─ Create React components in src/"
echo "   └─ Integrate with services"
echo "   └─ Connect to database via Supabase"
echo ""

echo "5. Test & Deploy"
echo "   └─ Follow DEPLOYMENT_CHECKLIST.md"
echo "   └─ Run tests"
echo "   └─ Deploy: npm run build"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✨ Your ERP system is ready to launch!"
echo ""
echo "📖 Read: 00_START_HERE.md"
echo "🚀 Run:  npm install && npm run dev"
echo ""
echo "════════════════════════════════════════════════════════════════"
