'use client';

import { useEffect, useState } from 'react';
import { Check, Clipboard, KeyRound, Loader2, Package } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { getMyDigitalLibrary, getMyDigitalSecret } from '@/app/(store)/actions';
import { useLocale } from '@/lib/locale-context';

type LibraryItem = { order_id: string; order_number: string; order_item_id: string; access_id: string; variant_id: string | null; product_title: string; unit_type: 'credential' | 'code'; delivered_at: string };

export function DigitalLibrary() {
  const { locale } = useLocale(); const ar = locale === 'ar';
  const [items, setItems] = useState<LibraryItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [revealed, setRevealed] = useState<Record<string, string>>({}); const [loadingId, setLoadingId] = useState<string | null>(null); const [copiedId, setCopiedId] = useState<string | null>(null);
  useEffect(() => { let active = true; void getMyDigitalLibrary().then((result) => { if (active) setItems(Array.isArray(result) ? result as LibraryItem[] : []); }).catch(() => { if (active) setError(ar ? 'تعذر تحميل مكتبتك الرقمية.' : 'Impossible de charger votre bibliothèque numérique.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [ar]);
  async function reveal(item: LibraryItem) { if (!window.confirm(ar ? 'هذه المعلومات خاصة. لا تشاركها.' : 'Ces informations sont privées. Ne les partagez pas.')) return; setLoadingId(item.order_item_id); setError(''); const result = await getMyDigitalSecret(item.order_id, item.order_item_id); setLoadingId(null); if (!result.success || typeof result.secret !== 'string') { setError(ar ? 'الوصول إلى المنتج غير متاح.' : 'Accès au produit indisponible.'); return; } setRevealed((current) => ({ ...current, [item.order_item_id]: result.secret as string })); }
  async function copy(item: LibraryItem) { const value = revealed[item.order_item_id]; if (!value) return; await navigator.clipboard.writeText(value); setCopiedId(item.order_item_id); window.setTimeout(() => setCopiedId(null), 1600); }
  return <section id="digital-library" className="border-t border-border pt-10"><div className="flex items-end justify-between gap-4 border-b border-border pb-5"><div><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-primary">03</p><h2 className="mt-2 font-heading text-2xl font-semibold">{ar ? 'مكتبتي الرقمية' : 'Ma bibliothèque numérique'}</h2></div><KeyRound className="h-5 w-5 text-primary" /></div>{error && <p role="alert" className="mt-5 border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</p>}{loading ? <div className="mt-6 h-24 animate-pulse border-y border-border bg-muted/20" /> : items.length === 0 ? <div className="mt-6 border-y border-border py-8"><Package className="h-7 w-7 text-primary" /><p className="mt-3 text-sm text-muted-foreground">{ar ? 'ستظهر المنتجات الرقمية هنا بعد الدفع والتسليم.' : 'Vos produits numériques apparaîtront ici après paiement et livraison.'}</p></div> : <div className="mt-6 divide-y divide-border border-y border-border">{items.map((item) => <article key={item.order_item_id} className="py-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-medium">{item.product_title}</p><p className="mt-1 text-xs text-muted-foreground">{item.unit_type === 'credential' ? (ar ? 'بيانات دخول' : 'Identifiants') : (ar ? 'رمز' : 'Code')} · {item.order_number}</p><p className="mt-1 text-xs text-muted-foreground">{ar ? 'تم التسليم' : 'Livré'} · {new Date(item.delivered_at).toLocaleDateString(ar ? 'ar-DZ' : 'fr-DZ')}</p></div>{revealed[item.order_item_id] ? <Button variant="outline" size="sm" onClick={() => copy(item)}>{copiedId === item.order_item_id ? <Check className="mr-2 h-4 w-4" /> : <Clipboard className="mr-2 h-4 w-4" />}{copiedId === item.order_item_id ? (ar ? 'تم النسخ' : 'Copié') : (ar ? 'نسخ' : 'Copier')}</Button> : <Button size="sm" onClick={() => reveal(item)} disabled={loadingId === item.order_item_id}>{loadingId === item.order_item_id && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}{ar ? 'عرض المنتج' : 'Voir les accès'}</Button>}</div>{revealed[item.order_item_id] && <div className="mt-4 rounded-md border border-primary/30 bg-primary/5 p-4"><p className="mb-2 text-xs font-medium text-muted-foreground">{ar ? 'معلومات خاصة' : 'Informations privées'}</p><pre className="whitespace-pre-wrap break-all font-mono text-sm">{revealed[item.order_item_id]}</pre></div>}</article>)}</div>}</section>;
}
