"use client"

import { useState } from "react"
import Link from "next/link"
import { ArrowRight, Check, Clipboard, CreditCard, MessageCircle, Send } from "lucide-react"
import { Button } from "@/components/ui/button"
import { formatPrice } from "@/lib/data"

type Settings = { flexyNumber: string; flexyInstructions: string; ccpInstructions: string; bankInstructions: string; facebook: string; telegramLink: string }

export function PaymentExperience({ paymentMethod, setPaymentMethod, isPending, onBack, onSubmit, settings, amount }: any) {
  const [stage, setStage] = useState<"method" | "instructions">("method")
  const [copied, setCopied] = useState(false)
  const methods = [
    { value: "flexy", title: "Flexy", description: "Payez rapidement depuis votre mobile.", configured: Boolean(settings.flexyNumber?.trim() && settings.flexyInstructions?.trim()) },
    { value: "ccp", title: "CCP", description: "Un transfert CCP, vérifié par notre équipe.", configured: Boolean(settings.ccpInstructions?.trim()) },
    { value: "bank_transfer", title: "Virement bancaire", description: "Un virement bancaire, vérifié par notre équipe.", configured: Boolean(settings.bankInstructions?.trim()) },
    { value: "slickpay", title: "SlickPay", description: "Bientôt disponible", disabled: true },
  ]
  const selected = methods.find((method) => method.value === paymentMethod) || methods[0]
  const instruction = paymentMethod === "flexy" ? settings.flexyInstructions : paymentMethod === "ccp" ? settings.ccpInstructions : settings.bankInstructions
  const copyNumber = async () => { if (!settings.flexyNumber) return; await navigator.clipboard?.writeText(settings.flexyNumber); setCopied(true); window.setTimeout(() => setCopied(false), 1600) }
  if (stage === "instructions") return <div className="border-t-2 border-foreground pt-6"><div className="flex items-start gap-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center bg-primary/10 text-primary"><CreditCard className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-primary">Paiement · {selected.title}</p><h2 className="mt-2 font-heading text-2xl font-semibold tracking-tight">Effectuez votre paiement</h2><div className="mt-7 space-y-5"><div className="border border-primary/30 bg-primary/5 p-5"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">Total à payer</p><p className="mt-2 font-heading text-3xl font-semibold tracking-tight">{formatPrice(amount)}</p></div>{paymentMethod === "flexy" && <div className="border border-border p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">Numéro Flexy</p><div className="mt-3 flex items-center justify-between gap-3"><p className="font-mono text-xl font-semibold tracking-wide">{settings.flexyNumber}</p><Button type="button" variant="outline" size="sm" onClick={copyNumber} className="gap-2"><Clipboard className="h-4 w-4" />{copied ? "Copié" : "Copier"}</Button></div></div>}<div className="border border-border p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">Instructions</p><p className="mt-3 whitespace-pre-line text-sm leading-7 text-muted-foreground">{instruction}</p></div><div className="flex gap-3"><Button type="button" variant="outline" onClick={() => setStage("method")}>Retour</Button><Button type="button" onClick={onSubmit} disabled={isPending || !selected.configured} className="h-12 gap-2">{isPending ? "Confirmation…" : "J’ai effectué le paiement"}<ArrowRight className="h-4 w-4" /></Button></div></div></div></div></div>
  return <div className="border-t-2 border-foreground pt-6"><div className="flex items-start gap-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center bg-primary/10 text-primary"><CreditCard className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-primary">Étape 3 · Paiement</p><h2 className="mt-2 font-heading text-2xl font-semibold tracking-tight">Comment souhaitez-vous payer ?</h2><div className="mt-5 border border-primary/30 bg-primary/5 p-5"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">Total à payer</p><p className="mt-2 font-heading text-3xl font-semibold">{formatPrice(amount)}</p></div><div className="mt-6 grid gap-3">{methods.map((method) => <button key={method.value} type="button" disabled={method.disabled || method.configured === false} onClick={() => !method.disabled && method.configured !== false && setPaymentMethod(method.value)} aria-pressed={paymentMethod === method.value} className={`flex w-full items-start justify-between border p-4 text-start transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary ${method.disabled || method.configured === false ? "cursor-not-allowed opacity-50" : "hover:border-primary"} ${paymentMethod === method.value ? "border-primary bg-primary/5" : "border-border bg-card"}`}><span><span className="block text-sm font-semibold">{method.title}</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{method.configured === false ? "Temporairement indisponible" : method.description}</span></span>{paymentMethod === method.value ? <Check className="mt-1 h-4 w-4 text-primary" /> : null}</button>)}</div><div className="mt-8 flex gap-3"><Button variant="outline" onClick={onBack}>Retour</Button><Button onClick={() => selected.configured && setStage("instructions")} disabled={!selected.configured} className="h-12 gap-2">{selected.configured ? "Voir les instructions" : "Méthode indisponible"}<ArrowRight className="h-4 w-4" /></Button></div></div></div></div>
}

export function ContinuationScreen({ orderNumber, orderId, paymentStatus, messenger, telegram }: { orderNumber: string; orderId: string; paymentStatus: string; messenger: string; telegram: string; isArabic?: boolean }) {
  return <div className="border-t-2 border-primary pt-8"><div className="flex h-14 w-14 items-center justify-center bg-primary text-primary-foreground"><Check className="h-7 w-7" /></div><p className="mt-8 text-[11px] font-semibold uppercase tracking-[0.2em] text-primary">Paiement transmis</p><h2 className="mt-3 font-heading text-3xl font-semibold tracking-tight">Comment souhaitez-vous continuer ?</h2><p className="mt-4 max-w-lg text-sm leading-7 text-muted-foreground">Votre paiement sera vérifié par notre équipe avant la confirmation de la commande.</p>{orderNumber && <p className="mt-6 border-y border-border py-4 text-sm">Référence : <span className="font-mono font-semibold">{orderNumber}</span></p>}<div className="mt-7 grid gap-3"><Link href={orderId ? `/account/orders/${orderId}` : "/account"} className="border-2 border-primary bg-primary/5 p-5 transition-colors hover:bg-primary/10"><span className="text-[10px] font-semibold uppercase tracking-[0.18em] text-primary">Recommandé</span><span className="mt-2 flex items-center justify-between gap-4"><span><span className="block text-base font-semibold">Continuer dans Edigiya</span><span className="mt-1 block text-sm text-muted-foreground">Gardez le suivi de votre commande dans Edigiya.</span></span><ArrowRight className="h-5 w-5 text-primary" /></span></Link><a href={messenger || "#"} target={messenger ? "_blank" : undefined} rel="noopener noreferrer" className="flex items-center justify-between border border-border p-5 transition-colors hover:border-primary"><span className="flex items-center gap-3"><MessageCircle className="h-5 w-5 text-primary" /><span><span className="block text-sm font-semibold">Messenger</span><span className="mt-1 block text-xs text-muted-foreground">Échangez avec notre équipe.</span></span></span><ArrowRight className="h-4 w-4" /></a><a href={telegram || "#"} target={telegram ? "_blank" : undefined} rel="noopener noreferrer" className="flex items-center justify-between border border-border p-5 transition-colors hover:border-primary"><span className="flex items-center gap-3"><Send className="h-5 w-5 text-primary" /><span><span className="block text-sm font-semibold">Telegram</span><span className="mt-1 block text-xs text-muted-foreground">Continuez la conversation avec notre équipe.</span></span></span><ArrowRight className="h-4 w-4" /></a></div></div>
}
